# Reference: https://docs.codecov.com/docs/commit-status

codecov:
  branch: master

coverage:
  range: 50..90
  round: down
  precision: 2
  status:
    project:
      default:
        threshold: 9%
    patch: off
